### PR TITLE
.env.local to work by default

### PR DESCRIPTION
**Pull request by woloski**
right now if I download this sample from quickstarts, it doesn't work because some values are not filled out. 

```
if (!baseUrl || !issuerBaseUrl || !audience) {
  throw new Error('Please make sure that the file .env.local is in place and populated');
}
```

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
Hey @woloski - thanks for the PR!

We recommend that our user's don't check `.env` files into their repos to prevent them accidentally leaking secrets, so in our samples we create an `env.local.template` , add `.env.local` to the `.gitignore` to be [ignored from the sourcecode](https://github.com/auth0-samples/auth0-nextjs-samples/blob/main/Sample-01/.gitignore#L34) and add [the following instructions to the README](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01#configure-credentials):

> copy .env.local.example into a new file in the same folder called .env.local, and replace the values with your own

If there is somewhere else you think we should add those instructions or anything else we can do to make it clearer, let me know

**Comment by woloski** [comment]
ok, but the values in env.local.template should include the stuff I added. Otherwise the sample doesn't work out of the box. Can you add that?

**Comment by adamjmcgrath** [comment]
Hey @woloski - happy to prefill `AUTH0_BASE_URL=http://localhost:3000` in [.env.local.template](https://github.com/auth0-samples/auth0-nextjs-samples/blob/main/Sample-01/.env.local.template)

But I'd rather require the user to provide their own secret, even if it means they have to hit that error if they forget.

**Comment by adamjmcgrath** [comment]
Also, @Widcket has updated the sample in #15 so it doesn't require `audience` any more

**Comment by woloski** [comment]
what if we set the secret to replace-with-your-own-secret-generated-with-openssl? and make that very clear in README.

Also, I learnt that the packager will look for .example (not .template) and remove the .example on the final package so that a user can run the sample out of the box. Can we rename it to env.local.example?

**Comment by adamjmcgrath** [comment]
> what if we set the secret to replace-with-your-own-secret-generated-with-openssl? and make that very clear in README.

sgtm 👍 

> Also, I learnt that the packager will look for .example (not .template) and remove the .example on the final package so that a user can run the sample out of the box. Can we rename it to env.local.example?

Ah, perfect

**Review by adamjmcgrath — APPROVED** [review]

**Pull request merged**
